ProgramInfo:
  program_name: web - Mirror-Elf by TG@seo898
  admin_domain: ''
  admin_ips: []
  authorization_code: EOXqt0eu2aphZ3ThMde3rbFKD0siGqF5CvYuXqnJhr1fwUjgxxkG5fHNZGo3VUxgNMdmtv0bizQOMjTScKp0CkHEBXyB
  login_account: admin
  login_password: admin
  pg_database_url: postgresql://admin:mirrorelf@localhost:5432/mirror
WebsiteSettings:
  target_get_method: doc_random
  target_doc_name: target.txt
  target_use_limit: gt0
  pan_site_target_get_method: doc_pop
  pan_site_target_doc_name: pan_target.txt
  pan_site_target_use_limit: lt2
  crawler_target: true
  tdk_mode: tem
  tdk_doc_name: tdk.txt
  titles:
  - '{@keyword #98} - {%Related(@keyword,{@keyword #98},2) #99} | {%Related(@keyword,{@keyword #98},2) #999}'
  keywords:
  - '{@keyword #98},{%Related(@keyword,{@keyword #98},2) #99},{%Related(@keyword,{@keyword #98},2) #999}'
  descriptions:
  - '{@description}'
  pan_site_tdk_mode: tem
  pan_site_tdk_doc_name: tdk.txt
  pan_site_titles:
  - '{@title}'
  pan_site_keywords:
  - '{@keyword}'
  pan_site_descriptions:
  - '{@description}'
  auto_site_building: true
  auto_https_certificate: false
  pan_site_auto_site_building: true
  pan_site_crawler_target: true
  language: zh
  link_mapping: false
  website_cache_index_over_time: 365
  website_cache_page_over_time: 365
  target_cache_index_over_time: 3650
  target_cache_page_over_time: 3650
  target_static_save: .js,.css,.jpg,.png
SEOFunctions:
  external_filter:
  - .gov.cn
  external_links:
  - '{随机网址}'
  meta_information: true
  random_div_attributes: true
  random_class_name: true
  head_header: ''
  head_footer: ''
  body_header: <h1><a target="_blank" title="{标题}" href="{首页}">{核心词}</a></h1>
  body_footer: |-
    <a target="_blank" href="{@push_link}">{@keyword}</a>
    <a target="_blank" href="{@push_link}">{@keyword}</a>
    <a target="_blank" href="{@push_link}">{@keyword}</a>
    <a target="_blank" href="{@push_link}">{@keyword}</a>
    <a target="_blank" href="{@push_link}">{@keyword}</a>
  html_entities: true
  friend_link_mode: all
  friend_link_count: 5
  friend_links:
  - <a target="_blank" title="{*主站.标题#1001}" href="{*主站.首页#1001}">{*主站.标题#1001}</a>
  seo_404_page: true
AccessPolicy:
  forced_domain_binding: false
  ip_site_referrer: true
  pan_site_referrer: true
  ua_banlist:
  - HttpClient
  - UniversalFeedParser
  - lightDeckReports Bot
  - heritrix
  - Java
  - Bytespider
  - YandexBot
  - FlightDeckReports
  - Indy Library
  - BOT/0.1
  - DigExt
  - Feedly
  - Swiftbot
  - oBot
  - Python-urllib
  - CrawlDaddy
  - YYSpider
  - JikeSpider
  - ZmEu
  - MJ12bot
  - WebZIP
  - Apache-HttpAsyncClient
  - HttpClient
  - WinHttp
  - jaunty
  - Alexa Toolbar
  - LinkpadBot
  - Microsoft URL Control
  - node-superagent
  - Ezooms
  - Jullo
  - SemrushBot
  - FetchURL
  - AhrefsBot
  - EasouSpider
  - java/
  - CoolpadWebkit
  - Linguee Bot
  ip_banlist: []
AdPolicy:
  ad_url: http://www.baidu.com
  search_referrer_jump_ad: false
  regular_ua_jump_ad: false
GlobalCodeInsertion:
  filter_ip:
  - 156.59.82.*
  head_header: <script src="/_/static/js/ad1.js" type="text/javascript"></script>
  head_footer: ''
  body_header: ''
  body_footer: ''
SpiderPolicy:
  baidu_spider: true
  sogou_spider: true
  yisou_spider: true
  byte_spider: true
  bing_spider: true
  so_spider: true
  google_img_spider: true
  google_spider: true
  quark_spider: true
  yahoo_spider: true
  other_spider: true
  user: true
